services:
    jrs-server:
        image: jasperserver:8.0.0
        container_name: jrs-server
        build:
            context: ./js-docker
            dockerfile: Dockerfile
            pull: false
            args:
                JAVA_BASE_IMAGE: openjdk@sha256:b577374a385b86572caad3050b122b6aa6dd911cf37421667d248e9d1c638e44
        volumes:
            - ./js-docker/license:/usr/local/share/jasperserver/license
            - ./js-docker/keystore:/usr/local/share/jasperserver/keystore
        env_file:
            - ./js-docker/jasperreports-server.env
        environment:
            - DB_HOST=jrs-postgresql
        depends_on:
            jrs-cmdline:
                condition: service_completed_successfully
        command: ['/entrypoint-ce.sh', 'run']
        ports:
            - 9090:8080
            - 9443:8443

    jrs-cmdline:
        image: jasperserver-cmdline:8.0.0
        container_name: jrs-cmdline
        build:
            context: ./js-docker
            dockerfile: Dockerfile-cmdline
            pull: false
            args:
                JAVA_BASE_IMAGE: openjdk@sha256:b577374a385b86572caad3050b122b6aa6dd911cf37421667d248e9d1c638e44
        volumes:
            - ./js-docker/license:/usr/local/share/jasperserver/license
            - ./js-docker/keystore:/usr/local/share/jasperserver/keystore
        env_file: ./js-docker/jasperreports-server.env
        environment:
            - DB_HOST=jrs-postgresql
            - JRS_LOAD_SAMPLES=false
        depends_on:
            - jrs-postgresql
        command: ['/wait-for-it.sh', 'jrs-postgresql:5432', '-t', '30', '--', '/entrypoint-cmdline-ce.sh', 'init']

    jrs-postgresql:
        image: postgres:12
        container_name: jrs-postgresql
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            - jrs_pgdata:/var/lib/postgresql/data
        ports:
            - 5434:5432

volumes:
    jrs_pgdata:
